import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  LoadingOutline,
  UserOutline,
  EditOutline,
  DeleteOutline,
  CheckCircleTwoTone,
  HomeOutline,
  SearchOutline,
  ArrowRightOutline,
  PlusSquareOutline,
  CalendarOutline,
  EnvironmentOutline,
  PhoneOutline,
  MailOutline,
  IdcardOutline,
  MobileOutline,
  TeamOutline,
  FolderOutline,
  GlobalOutline,
  FileAddOutline,
  LockOutline,
  FacebookOutline,
  GoogleOutline,
  FileProtectOutline,
  ProfileOutline,
  SettingOutline,
  ReloadOutline,
  ShoppingOutline,
  LogoutOutline,
  FieldNumberOutline,
} from '@ant-design/icons-angular/icons';

const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  LoadingOutline,
  UserOutline,
  EditOutline,
  DeleteOutline,
  CheckCircleTwoTone,
  ArrowRightOutline,
  HomeOutline,
  SearchOutline,
  PlusSquareOutline,
  CalendarOutline,
  EnvironmentOutline,
  PhoneOutline,
  MailOutline,
  IdcardOutline,
  MobileOutline,
  TeamOutline,
  FolderOutline,
  GlobalOutline,
  FileAddOutline,
  LockOutline,
  FacebookOutline,
  GoogleOutline,
  FileProtectOutline,
  ProfileOutline,
  SettingOutline,
  ReloadOutline,
  ShoppingOutline,
  LogoutOutline,
  FieldNumberOutline,
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {}
